swagger: "2.0"
info:
  description: ""
  version: "0.0.1"
  title: "Cyber fighters backyard REST API"
host: localhost:8080
basePath: /v1
schemes:
- http
securityDefinitions:
  basicAuth:
    type: basic
    x-basicInfoFunc: backyard.api.rest.auth.requires_auth
tags:
- name: user
  description: User management and authentication
- name: analysis
  description: Listing and triggering analyzer runs
- name: ws
  description: Websocket Eventing
- name: analyzers
  description: Handle available analyzers
consumes:
- application/json
produces:
- application/json
paths:
  #  /user/login:
  #    post:
  #      tags:
  #      - user
  #      summary: Logs user into the system
  #      x-swagger-router-controller: "backyard.api.rest.routes.user"
  #      operationId: "login"
  #      parameters:
  #      - in: body
  #        name: credentials
  #        schema:
  #          $ref: '#/definitions/Login'
  #      responses:
  #        200:
  #          description: OK
  #        400:
  #          description: Bad request. User ID must be an integer and larger than 0.
  #        401:
  #          description: Authorization information is missing or invalid.
  #        404:
  #          description: A user with the specified ID was not found.
  #        default:
  #          description: Unexpected error.
  #  /user/logout:
  #    get:
  #      tags:
  #      - user
  #      security:
  #        - basicAuth: []
  #      summary: Logs out current logged in user
  #      description: |
  #        Invalidates the served JWT. Using the API needs a new JWT.
  #      x-swagger-router-controller: "backyard.api.rest.routes.user"
  #      operationId: "logout"
  #      responses:
  #        '200':
  #          description: OK
  /analyzers/:
    get:
      security:
      - basicAuth: []
      tags:
      - analyzers
      summary: Get a list of available analyzers
      x-swagger-router-controller: "backyard.api.rest.routes.analyzers"
      operationId: "list"
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/ListAnalyzerResponse"
        404:
          description: no analyzers available
        504:
          description: Timeout
  /analysis/:
    post:
      security:
      - basicAuth: []
      tags:
      - analysis
      summary: Start a new analysis
      x-swagger-router-controller: "backyard.api.rest.routes.analysis"
      operationId: "create"
      parameters:
      - name: request
        in: body
        required: true
        schema:
          $ref: '#/definitions/AnalyserRequest'
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/AnalyserResponse"
        400:
          description: Invalid ID supplied
        404:
          description: Analysis not found
        500:
          description: Analysis could not be started
        504:
          description: Timeout
    get:
      security:
      - basicAuth: []
      tags:
      - analysis
      summary: Get a list of analyses
      x-swagger-router-controller: "backyard.api.rest.routes.analysis"
      operationId: "listAnalyses"
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: "#/definitions/Analysis"
  /analysis/{id}:
    get:
      security:
      - basicAuth: []
      tags:
      - analysis
      summary: Get analysis by ID
      x-swagger-router-controller: "backyard.api.rest.routes.analysis"
      operationId: "read"
      parameters:
      - name: id
        in: path
        description: The ID of the analysis
        required: true
        type: string
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/Analysis"
        400:
          description: Invalid ID supplied
        404:
          description: Analysis not found
    delete:
      security:
      - basicAuth: []
      tags:
      - analysis
      summary: Delete analysis
      x-swagger-router-controller: "backyard.api.rest.routes.analysis"
      operationId: "delete"
      description: This can only be done by the logged in user.
      parameters:
      - name: id
        in: path
        description: The ID of the analysis
        required: true
        type: string
      responses:
        200:
          description: OK
        400:
          description: Invalid ID supplied
        404:
          description: Analysis not found
        500:
          description: Error deleting analyzer entry
  /ws:
    get:
      security:
      - basicAuth: []
      tags:
      - ws
      summary: Websocket endpoint to subscribe to for status updates
      x-swagger-router-controller: "backyard.api.rest.routes.ws"
      operationId: "subscribe"
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/JobStatus'
definitions:
  Status:
    type: string
    description: Current scan/analyzer status
    enum:
    - READY
    - PENDING
    - WAITING
    - SCANNING
    - ANALYZING
    - TIMEOUT
    - ERROR
  Scanner:
    type: string
    description: Analyser types
    enum:
    - NONE
    - HARVESTER
    - SPIDERFOOT
  ResultCode:
    type: string
    description: Common response codes
    enum:
    - OK
    - FAIL
  Login:
    type: object
    properties:
      username:
        type: string
      password:
        type: string
  AnalyserRequest:
    type: object
    properties:
      domain:
        type: string
        example: tuev-sued.de
        description: Domain parameter to be scanned
      analyzer:
        type: string
        example: DUMMY1
        description: Name of the analyzer to be run
  AnalyserResponse:
    type: object
    properties:
      code:
        $ref: '#/definitions/ResultCode'
      id:
        type: string
        description: Unique ID for this analyser run
  ListAnalyzerResponse:
    type: array
    items:
      $ref: '#/definitions/AnalyzerInfo'
  AnalyzerInfo:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      description:
        type: string
      scanners:
        type: array
        items:
          $ref: '#/definitions/ScannerInfo'
  ScannerInfo:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      description:
        type: string
  Analysis:
    type: object
    properties:
      id:
        type: string
        description: ID of the analyzer run
      domain:
        type: string
        description: Domain parameter that is scanned
      progress:
        type: integer
        format: uint32
        description: Approximated percent completed
      completed:
        type: boolean
        description: Completion status of the analysis
      status:
        $ref: '#/definitions/Status'
        description: Current analyzer status
      scanners:
        type: array
        description: List of used scanner IDs
        items:
          type: string
  JobStatus:
    type: object
    properties:
      id:
        type: string
        description: ID of the analyzer run
      status:
        $ref: '#/definitions/Status'
      description:
        type: string
        description: Optional description i.e. for certain scan stages
      completed:
        type: integer
        format: in32
        description: Approximated percent completed
        minimum: 0
        maximum: 100
