language: python

python:
- "3.6"

before_install:
  - sudo apt update

install:
  - "pip install flake8"
  - "pip install pylint"
  - "sudo apt install shellcheck"

script:
  - shellcheck **/*.sh
  - flake8 **/*.py
  - pylint **/*.py
