analyzer:
  id: "EXAMPLE"
  name: "Runner for the dummy example scanner"
  description: |
    Tests an analyzer with just one depenendent scanner.
  image: "backyard/analyzer-example:latest"
  scanners:
  - EXAMPLE
